[linters-settings.lll]
line-length = 120

[linters]
enable-all = true
disable = [
    "tenv",
    "godox",
    "gofumpt"
]

[linters-settings.revive.rules]
name = "var-naming"
severity = "warning"
disabled = true
exclude = [""]
arguments = [
    ["ID"],     # AllowList
    [{ upperCaseConst = true }]  # Extra parameter
]
