version = '2'

[linters]
default = 'all'
disable = [
  'godox',
  'wsl'
]
enable = [
    'wsl_v5'
]

[linters.settings]
[linters.settings.wsl_v5]
allow-first-in-block = true
allow-whole-block = false
branch-max-lines = 2

[linters.settings.lll]
line-length = 120

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = 'unused-parameter'
disabled = true

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gci',
  'gofmt',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]