name: Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Test
        run: go test -v ./...


  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.22', '1.23' ]

    name: Go ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...